### ISSUE TITLE
Change str to glimpse

### ISSUE THREAD

**Issue by statunizaga** [brry/berryFunctions#6]
Hi dude, your package is awesome, just a suggestion may you change str function to glimpse from dplyr.
Because the appareance of glimpse looks better than str function.

**Comment by brry** [comment]
Thanks! Solved in https://github.com/brry/rskey/issues/1

**Comment by statunizaga** [comment]
> Thanks! Solved in [brry/rskey#1](https://github.com/brry/rskey/issues/1)

I installed again the new version but it is still using the last function(str)


![image](https://user-images.githubusercontent.com/44730806/182039696-34ae892d-8214-46e5-ba5b-e7b8ccca71c7.png)
